language: node_js
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
jobs:
  include:
  - stage: test
    script:
    - npm run lint
    - npm test
    - npm run coverage
  - stage: deploy
    install: true
    if: branch = release/demo
    script:
    - echo 'Deploying to NOW'
    - npm install -g now
    - npm run deploy-demo && npm run alias-demo
  - stage: deploy
    install: true
    if: branch = release/playground
    script:
    - echo 'Deploying to NOW'
    - npm install -g now
    - npm run deploy-playground && npm run alias-playground
  - stage: build docker image
    sudo: true
    services:
        - docker
    install: true
    if: tag IS present
    script:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t wt-read-api:$TRAVIS_BRANCH .
    - docker tag wt-read-api:$TRAVIS_BRANCH 029479441096.dkr.ecr.eu-west-1.amazonaws.com/wt-read-api:$TRAVIS_BRANCH
    - docker push 029479441096.dkr.ecr.eu-west-1.amazonaws.com/wt-read-api:$TRAVIS_BRANCH
env:
  global:
  - secure: eQMrwJ4qlU76kI/a9cOoUYZZrDqL9PQ3BpbzQFDBnuPmcRYeMohaQo/JEv3lw3yrIHgNMEXvpwEUbjG0DoumuM7g8kVQCQ2rZZjvVspnTX+xWiF3YuIyb4fQGJL2g6YQDYjSlnYH+e4p3TrrjmQBHLc0VdFe04hkUcp4zCxYdKjFDRUpl2guqJWPMrCv3muh31jgnqlOCnTAI6GCcNAeuIXdfknNQRHdQ2z1YKH3Z24QS9TOiG+fTtlgKeKfOgs7Q3mnPlwcFUjAbpQn5jib490iMT1kQdPE09Jl1bUI2wdejXGTBHwEyr/zMm6I+ZYFld6FILKwadao+KwZRu8Ks/e5LIqM17KHhe2j5eALkEQwl91dUhdQm5aH6eKfUOA8yEfoYZhRjJiMK4QXb6mPDp1LdruErMe0qu+Y7JHPAb2km8HPpLDsOZglD9l+HPJpJ4iOCAgzr+AgawFStzZWEhWD+dlS3nhoFzJOldCVeaV2Bug3Jlr6Jl57i6QKOxKGck/v4Mep3871cfxbhik89YcR3c5YKcBrb3fx88dgjdP5kHzhL6TXgirL9ffBt6wFaZo8Qxlti6+jd+a8r6Lkop0Te899LVR5R7dF2TrkmqMwBtgd7fDaazODlN5bQoFefGyihIUIwQQ2yVjETPeIUdKGhiLM9hbUlCQoPQ/lkEM=
  - secure: ZuGWaKHwqK+kgX6xWzQ9GiiMvE0w3lbbQI2gQT8cJpwOvRzFlzc0UoGbCPEUOiaCboBhmjeaonmB+3oibvu7lwejPijBeqLZ6/yQ7JSmNxNs6j5pM56AYaeEfeQYVDjI08vLBcVh4ZWq/wOix8aXWA4d69wSdDYoYv+GcKPi99ZK6tfDxWMwHaDbCJC6JZrBjMDShFTQnuKqHwIcuTBiA+n8KDtGLS3TvT8GdIDLOrk7W6wsO+Pw8ViBZx6nXGEOlHCV4pJE8jFmqNzyGoco4wutenyoTh3nIkTgpFnL2T1q1gIQ9t99Sz4JENvIXYp0rR0MLLXJ7ZYNioF9DX0LK34SAkOq/XXvri4H0L1AnoxB12uGNGyVlI08jk2k4pT9oqZ+aaegtLaGR1j9h9hKltUcORbsQ+OXdEycGEtrsHM58YKAcrWYnDtkHBD5QfPtj29JlMBwwKUpPVz+MQqCSdGSoMN1BDDDxaltr7rsiA4320rxMaBoWDCN0I2nolSuf1NHx9xzj6sdhkEfBzIMxmoRkcA9G2XqLr5bu6ET80CSPjaax2CPyiSSZGLtLlnmeeMzcwoevMLMM4XWNV78J3+pgtqykoaRYBN4PI9fBFrRxmNzv1vfQh05cZ3lAmhABYispuF02VOBzDUQhwHaY+SJXbZDHT3U+TFMIG5IZC8=
